### ISSUE TITLE
Migration of Oomph Incubator to Orbit

### ISSUE THREAD

**Issue by merks** [merks/orbit-simrel#1]
FYI @akurtakov and @jonahgraham

I have created the following jobs:

- https://ci.eclipse.org/orbit/job/maven-osgi-test/
- https://ci.eclipse.org/orbit/job/maven-bnd-test/
- https://ci.eclipse.org/orbit/job/orbit-aggregation-test/

Each is driven by a *.jenkinsfile and each promotes into the corresponding folder here:

- https://download.eclipse.org/justj/?file=tools/orbit/test

Orbit's CI instance now has a PGP key as well as a dash token for opening iplab issues on github, e.g., this has been opened automatically.

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9229

### maven-osgi

This update site is the combined and updated set of direct-from-maven dependencies that are available as OSGi bundles:

https://download.eclipse.org/tools/orbit/test/maven-osgi/

The inputs (from SimRel projects' target platforms) are reported here:

https://github.com/merks/orbit-simrel/tree/master/report/maven-osgi

This includes the supplement that I defined to ensure that all requirements of this repository resolve along with some extra things that are useful for projects such as Mylyn which is not using a Maven target:

https://github.com/merks/orbit-simrel/blob/master/maven-osgi/tp/other/MavenSupplement.target

All the bundles of this update site are PGP signed with Orbit's PGP key (and the build uses the simplified/enhanced PGP signing support available in the Tycho 4.0.0 release, e.g., to ensure that JCE-jar-signed bundles, which are not rooted in the cacerts are automatically PGP signed without using a force list).

### maven-bnd

This update site is the content that uses a Maven (m2e) target location to wrap jars into OSGi bundles:

https://download.eclipse.org/tools/orbit/test/maven-bnd/

This is the key input to drive the content:

https://github.com/merks/orbit-simrel/blob/master/maven-bnd/tp/MavenBND.target

All the bundles are jar signed.

The BND tools provide **really nice** views/editors for reviewing the details of the generated/wrapped OSGi bundles:

![image](https://github.com/merks/orbit-simrel/assets/208716/9a9aea0d-89a3-49e7-9d27-430db13d784e)

As requested, joni and jcodings are also included now and lucene is updated to version 9.7.0.

### orbit-aggregation

This update site is the aggregation of the "normal Orbit repository",  the two sites above, and and an older CVS-supporting release or Orbit to ensure that the aggregation is complete with respect to all requirements being satisfiable.

https://download.eclipse.org/tools/orbit/test/orbit-aggregation/

It's driven by this definition:

https://github.com/merks/orbit-simrel/blob/master/orbit-aggregation/orbit.aggr

The build can and does replace the input sites with those specified by the parameters, though the above are the default parameter values.

Anything not already validly jar signed nor PGP signed is PGP signed by this build, i.e., older legacy jars will be PGP signed if needed.

There is a corresponding orbit.aggran for deeper analysis.   Here I've slightly modified the platform's repository to contribute to the aggregation rather than just be a validation repository so that we can see easily why it's required.

![image](https://github.com/merks/orbit-simrel/assets/208716/28efb57f-4859-4dc9-b65a-851e6c024944)

In any case, we can see which "legacy" bundles are being dragged in because of the requirements of other content.

**Comment by jonahgraham** [comment]
This looks great Ed. Sorry for the silence - I'm guilty of ["lazy consensus"](https://www.eclipse.org/lists/eclipse.org-architecture-council/msg04618.html)

**Comment by jonahgraham** [comment]
I guess the next steps are:

- Move the URL from test to something permanent
- Announce this
- Update some parts of https://download.eclipse.org/tools/orbit/downloads/ to redirect/mention the new stuff.
